title: Tingnan Bao
description: Academic homepage for Dr. Tingnan Bao, Research Associate at the University of Ottawa.
url: ""
baseurl: ""
linkedin: https://ca.linkedin.com/in/tingnan
google_scholar: https://scholar.google.com/citations?user=zulfBIIAAAAJ

author:
  name: Dr. Tingnan Bao
  role: Research Associate, University of Ottawa
  location: Ottawa, ON, Canada

markdown: kramdown
plugins:
  - jekyll-seo-tag

exclude:
  - .bundle
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - _site
